import json
import time

from odoo import api, fields, models
from odoo.osv.expression import Domain
from odoo.exceptions import AccessError, UserError


class McpAgentTool(models.Model):
    _name = "mcp.agent.tool"
    _description = "MCP Agent Tool"
    _order = "sequence, id"

    name = fields.Char(required=True)
    model = fields.Char(required=True)
    method = fields.Selection(
        selection=[
            ("search_records", "Search records"),
            ("get_record", "Get record"),
            ("create_record", "Create record"),
            ("update_record", "Update record"),
            ("delete_record", "Delete record"),
            ("generate_dashboard", "Generate dashboard"),
            ("generate_webapp", "Generate web app"),
        ],
        required=True,
    )
    description = fields.Text()
    group_ids = fields.Many2many("res.groups", string="Allowed Groups")
    return_type = fields.Text(default="{}", help="JSON schema-like response contract.")
    sequence = fields.Integer(default=10)
    active = fields.Boolean(default=True)

    _sql_constraints = [
        models.Constraint("mcp_agent_tool_name_unique", "unique(name)", "Tool name must be unique."),
    ]

    @api.constrains("return_type")
    def _check_return_type(self):
        for tool in self:
            if tool.return_type:
                json.loads(tool.return_type)

    def _check_group_access(self):
        for tool in self:
            if tool.group_ids and not (tool.group_ids & self.env.user.groups_id):
                raise AccessError("You are not allowed to run this MCP tool.")

    def execute_tool(self, payload=None):
        self.ensure_one()
        payload = payload or {}
        self._check_group_access()

        server = self.env["mcp.server"].search([("active", "=", True)], limit=1)
        if not server:
            raise UserError("No active MCP server configuration found.")
        server.check_rate_limit(self.env.user)
        if not server._is_model_allowed(self.model):
            raise AccessError(f"Model '{self.model}' is not allowed by MCP server policy.")

        start = time.monotonic()
        status = "success"
        response_payload = {}
        try:
            method = getattr(self, f"_exec_{self.method}")
            response_payload = method(payload)
            return response_payload
        except Exception as error:  # noqa: BLE001
            status = "failed"
            response_payload = {"error": str(error)}
            raise
        finally:
            self.env["mcp.activity.log"].create({
                "user_id": self.env.user.id,
                "tool_id": self.id,
                "request_payload": json.dumps(payload),
                "response_payload": json.dumps(response_payload),
                "status": status,
                "duration_ms": int((time.monotonic() - start) * 1000),
            })

    def _exec_search_records(self, payload):
        model_name = payload.get("model", self.model)
        domain = Domain(payload.get("domain", []))
        limit = int(payload.get("limit", 20))
        records = self.env[model_name].search(domain, limit=limit)
        return {"ids": records.ids, "count": len(records)}

    def _exec_get_record(self, payload):
        model_name = payload.get("model", self.model)
        record = self.env[model_name].browse(payload["id"]).exists()
        if not record:
            raise UserError("Record not found.")
        fields_list = payload.get("fields") or ["display_name"]
        return {"record": record.read(fields_list)[0]}

    def _exec_create_record(self, payload):
        record = self.env[payload.get("model", self.model)].create(payload.get("values", {}))
        return {"id": record.id, "display_name": record.display_name}

    def _exec_update_record(self, payload):
        record = self.env[payload.get("model", self.model)].browse(payload["id"]).exists()
        if not record:
            raise UserError("Record not found.")
        record.write(payload.get("values", {}))
        return {"id": record.id, "display_name": record.display_name}

    def _exec_delete_record(self, payload):
        record = self.env[payload.get("model", self.model)].browse(payload["id"]).exists()
        if not record:
            raise UserError("Record not found.")
        record.unlink()
        return {"id": payload["id"], "deleted": True}

    def _exec_generate_dashboard(self, payload):
        dashboard = self.env["mcp.echart.dashboard"].create({
            "name": payload.get("name", "Generated Dashboard"),
            "model_source": payload.get("model", self.model),
            "query": json.dumps(payload.get("domain", [])),
            "options": json.dumps(payload.get("options", {"title": {"text": "Generated"}})),
            "code": payload.get("code", "# Generated by MCP tool"),
        })
        return {"dashboard_id": dashboard.id, "name": dashboard.name}

    def _exec_generate_webapp(self, payload):
        app = self.env["mcp.webapp"].create({
            "name": payload.get("name", "Generated Web App"),
            "slug": payload.get("slug") or f"generated-{fields.Datetime.now().timestamp():.0f}",
            "code_js": payload.get("code_js", "export default function App(){return <h1>MCP App</h1>; }"),
            "endpoints": json.dumps(payload.get("endpoints", [])),
            "public_access": bool(payload.get("public_access", False)),
        })
        return {"webapp_id": app.id, "slug": app.slug}
